name: stylegan3

channels:
  - nvidia
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy>=1.20
  - click>=8.0
  - pillow
  - scipy
  - requests
  - tqdm
  - ninja
  - matplotlib
  - imageio

  - pip:
    - --index-url https://download.pytorch.org/whl/cu130
    - --extra-index-url https://pypi.org/simple
    - torch==2.9.1
    - torchvision==0.24.1
    - torchaudio==2.9.1
    - imageio-ffmpeg==0.4.3
    - pyspng
